modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="compartido"
version="1.0.0"
displayName="Compartido"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="aguam, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.compartido]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.compartido]]
    modId="mcreator_link"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.compartido]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

